# Generated by Django 5.1.7 on 2025-03-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='colors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userimage',
            name='labels',
            field=models.TextField(blank=True, null=True),
        ),
    ]
